"""add phone number in users

Revision ID: b81792377138
Revises: 98c60ebfd683
Create Date: 2022-08-19 15:48:21.163504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81792377138'
down_revision = '98c60ebfd683'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
